#!/usr/bin/bash

OUT_DIR=$1

python3 career-translate.py origs/careers.db > "$OUT_DIR/packs/careers.db"
python3 translate.py origs/skills.db skills > "$OUT_DIR/packs/skills.db"
python3 translate.py origs/talents.db talents > "$OUT_DIR/packs/talents.db"
python3 rolltable-translate-db.py origs/tables.db > "$OUT_DIR/packs/tables.db"
python3 generator-translate.py origs/wfrp4e.js > "$OUT_DIR/wfrp4e.js"
python3 bestiary-translate.py origs/bestiary.db > "$OUT_DIR/packs/bestiary.db"
